branch-defaults:
  master:
    environment: beta3-env
global:
  application_name: beta3
  default_ec2_keyname: beanstalk-west
  default_platform: 64bit Amazon Linux 2015.03 v1.3.1 running Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
packages:
  yum:
    git: []